# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Settings
runtime_include_emi=true

# Gradle Configuration
artifact_name=my-mod

# Publishing
compatible_minecraft_versions=1.21.1
curseforge_project=PROJECT_ID_GOES_HERE
curseforge_project_slug=my-mod
curseforge_project_relations=tesseract-api-neoforge:required
modrinth_project=PROJECT_ID_GOES_HERE
modrinth_project_slug=my-mod
modrinth_project_relations=tesseract-api:required
mod_discord_icon=URL_TO_MOD_ICON_IMAGE_GOES_HERE

# NeoForge Environment
minecraft_version=1.21.1
minecraft_version_range=1.21.1
neoforge_version=21.1.62
parchment_mappings_minecraft_version=1.21
parchment_mappings_version=2024.07.28
loader_version_range=[4,)

# Mod Properties
mod_id=my_mod
mod_name=My Mod
mod_group_id=net.swedz
mod_authors=Swedz
mod_description=My mod description
mod_github=https://github.com/Swedz/NeoForge-Mod-Template

# Dependencies
mixinextras_version=0.3.5
emi_version=1.1.10+1.21
emi_version_range=[1.1.10, 1.2-)
tesseract_version=1.6.6-beta-1.21.1
tesseract_version_range=[1.6.4-beta-, 1.7-)