# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Gradle Configuration
artifact_name=velocity-support

# Publishing
deploy_name=NeoForged Velocity Support
deploy_discord_icon=https://cdn.discordapp.com/emojis/1455359753600499762.webp
compatible_minecraft_versions=1.21.1
curseforge_project=1416157
curseforge_project_slug=neoforged-velocity-support
curseforge_project_relations=
modrinth_project=BIU6vvRc
modrinth_project_slug=neoforged-velocity-support
modrinth_project_relations=

# NeoForge Environment
minecraft_version=1.21.1
minecraft_version_range=1.21.1
neoforge_version=21.1.209
parchment_mappings_minecraft_version=1.21
parchment_mappings_version=2024.07.28
loader_version_range=[4,)

# Mod Properties
mod_id=velocity_support
mod_name=Velocity Support
mod_group_id=net.swedz
mod_authors=Swedz
mod_description=Adds support for Velocity's Modern Forwarding in NeoForge.
mod_github=https://github.com/Swedz/NeoForged-Velocity-Support