# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Gradle Configuration
artifact_name=velocity-support

# Publishing
compatible_minecraft_versions=1.21.11
curseforge_project=1416157
curseforge_project_slug=neoforged-velocity-support
curseforge_project_relations=
modrinth_project=BIU6vvRc
modrinth_project_slug=neoforged-velocity-support
modrinth_project_relations=
mod_discord_icon=URL_TO_MOD_ICON_IMAGE_GOES_HERE

# NeoForge Environment
minecraft_version=1.21.11
minecraft_version_range=1.21.11
neoforge_version=21.11.16-beta
parchment_mappings_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12
loader_version_range=[4,)

# Mod Properties
mod_id=velocity_support
mod_name=Velocity Support
mod_group_id=net.swedz
mod_authors=Swedz
mod_description=Adds support for Velocity's Modern Forwarding in NeoForge.
mod_github=https://github.com/Swedz/NeoForged-Velocity-Support